### ISSUE TITLE
Некорректно работает сценарий синхронизации с пустым репо

### ISSUE THREAD

**Issue by EvilBeaver** [TeamBIOS/cfg_tools#1]
```
Как пользователь 
Я хочу синхронизировать свое хранилище с чистым удаленным репо GIT

Когда я указал в файле настроек адрес хранилища
 И указал в файле настроек адрес удаленного репо
 И запустил команду run.py init файл_настроек
Тогда я вижу в логе, как инициализирован репо и создан файл авторов.
```

Сценарий выше не работает, т.к. пытается еще выполниться git pull, а удаленный репо - пустой.

По той же причине не работает export. Он сначала пытается делать pull, но падает. Выгрузка не происходит.

Требуется:
- При init не выполнять pull
- При export добавить ключ ком. строки позволяющий отменить pull (или иным образом его выключить на чистом репо)

**Comment by EvilBeaver** [comment]
Первый нах! ))

**Comment by TeamBIOS** [comment]
Окей, исправим, также наверное надо сделать команду clone

**Comment by TeamBIOS** [comment]
Исправлено
